\set ON_ERROR_STOP on

CREATE TABLE IF NOT EXISTS flux_browser.schema_version (
    version integer PRIMARY KEY,
    applied_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS flux_browser.settings (
    setting_key varchar(80) PRIMARY KEY,
    setting_value text NOT NULL,
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS flux_browser.bookmark_folders (
    folder_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_folder_id bigint
        REFERENCES flux_browser.bookmark_folders(folder_id)
        ON DELETE CASCADE,
    name varchar(160) NOT NULL,
    position integer NOT NULL CHECK (position >= 0),
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS flux_browser.bookmarks (
    bookmark_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    folder_id bigint
        REFERENCES flux_browser.bookmark_folders(folder_id)
        ON DELETE SET NULL,
    title varchar(500) NOT NULL,
    url text NOT NULL,
    position integer NOT NULL CHECK (position >= 0),
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT bookmarks_url_not_blank CHECK (length(trim(url)) > 0)
);

CREATE TABLE IF NOT EXISTS flux_browser.visits (
    visit_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url text NOT NULL,
    title varchar(500) NOT NULL,
    visited_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT visits_url_not_blank CHECK (length(trim(url)) > 0)
);

CREATE TABLE IF NOT EXISTS flux_browser.downloads (
    download_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_url text NOT NULL,
    file_name varchar(500) NOT NULL,
    target_path text,
    status varchar(24) NOT NULL,
    bytes_downloaded bigint NOT NULL DEFAULT 0 CHECK (bytes_downloaded >= 0),
    total_bytes bigint CHECK (total_bytes IS NULL OR total_bytes >= 0),
    started_at timestamptz NOT NULL DEFAULT now(),
    completed_at timestamptz,
    failure_message text,
    CONSTRAINT downloads_status_valid CHECK (
        status IN ('QUEUED', 'RUNNING', 'COMPLETED', 'CANCELLED', 'FAILED')
    )
);

CREATE TABLE IF NOT EXISTS flux_browser.speed_dial_entries (
    speed_dial_id uuid PRIMARY KEY,
    title varchar(160) NOT NULL,
    url text NOT NULL,
    position integer NOT NULL UNIQUE CHECK (position >= 0),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT speed_dial_url_not_blank CHECK (length(trim(url)) > 0)
);

CREATE TABLE IF NOT EXISTS flux_browser.browser_sessions (
    session_id uuid PRIMARY KEY,
    started_at timestamptz NOT NULL DEFAULT now(),
    saved_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS flux_browser.session_tabs (
    tab_id uuid PRIMARY KEY,
    session_id uuid NOT NULL
        REFERENCES flux_browser.browser_sessions(session_id)
        ON DELETE CASCADE,
    position integer NOT NULL CHECK (position >= 0),
    url text,
    title varchar(500) NOT NULL,
    pinned boolean NOT NULL DEFAULT false,
    selected boolean NOT NULL DEFAULT false,
    zoom numeric(4, 2) NOT NULL DEFAULT 1.00
        CHECK (zoom BETWEEN 0.50 AND 2.00),
    start_page boolean NOT NULL DEFAULT true,
    UNIQUE (session_id, position)
);

CREATE TABLE IF NOT EXISTS flux_browser.recently_closed_tabs (
    closed_tab_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url text,
    title varchar(500) NOT NULL,
    pinned boolean NOT NULL DEFAULT false,
    zoom numeric(4, 2) NOT NULL DEFAULT 1.00
        CHECK (zoom BETWEEN 0.50 AND 2.00),
    start_page boolean NOT NULL DEFAULT false,
    closed_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS flux_browser.window_state (
    singleton boolean PRIMARY KEY DEFAULT true CHECK (singleton),
    x double precision,
    y double precision,
    width double precision NOT NULL DEFAULT 1280 CHECK (width >= 900),
    height double precision NOT NULL DEFAULT 800 CHECK (height >= 640),
    maximized boolean NOT NULL DEFAULT false,
    fullscreen boolean NOT NULL DEFAULT false,
    updated_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO flux_browser.schema_version (version)
VALUES (3)
ON CONFLICT (version) DO NOTHING;
